apiVersion:  kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: snapshot-crds
  namespace: flux-system
resources:
  - snapshot.storage.k8s.io_volumesnapshotclasses.yaml
  - snapshot.storage.k8s.io_volumesnapshotcontents.yaml
  - snapshot.storage.k8s.io_volumesnapshots.yaml
spec:
  dependsOn:
    - name: aws-ebs-csi-driver
