apiVersion: v1
kind: ConfigMap
metadata:
  name: pulumi-configmap
  namespace: pulumi
  labels:
    bot: conformitron
data:
  Namespace: pulumi
  prNumber: "212"
  commitHash: c96ebaf8f8bbb188ed8217639eae25a341e1eabb
  deployed: "1707771256"
  env: common
