apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-csi
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: jiva.csi.openebs.io
allowVolumeExpansion: true
parameters:
  cas-type: jiva
  policy: openebs-jiva-default-policy