apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
  name: ebs-sc
provisioner: ebs.csi.aws.com
parameters:
  type: sbg1
volumeBindingMode: WaitForFirstConsumer