---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openebs
  namespace: kube-system
spec:
  chart:
    spec:
      chart: openebs
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: openebs
        namespace: kube-system
      version: "3.3.0"
  interval: 60s
  targetNamespace: kube-system
  values: 
    jiva:
      enabled: true
  
