---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ebs-csi-driver
  namespace: kube-system
spec:
  chart:
    spec:
      chart: aws-ebs-csi-driver
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: botkube
        namespace: flux-system
      version: 2.11.1
  interval: 60s
  targetNamespace: kube-system
  values: 
    controller:
      region: snow
      env:
      - name: AWS_EC2_ENDPOINT
    node:
      env:
      - name: AWS_EC2_ENDPOINT
      - name: AWS_REGION
        value: snow
  valuesFrom:
  - kind: Secret
    name: aws-ebs-csi-driver-secret
    valuesKey: device-ip
    targetPath: controller.env[0].value
  - kind: Secret
    name: aws-ebs-csi-driver-secret
    valuesKey: device-ip
    targetPath: node.env[0].value

