apiVersion: v1
kind: ConfigMap
metadata:
  name: newrelic-configmap
  namespace: newrelic
  labels:
    bot: conformitron
data:
  Namespace: newrelic
  prNumber: "284"
  commitHash: 574a13d80e0395dd51ecb86a43b2dac34ce81c9c
  deployed: "1721131397"
  env: vsphere
