apiVersion: v1
kind: ConfigMap
metadata:
  name: newrelic-configmap
  namespace: newrelic
  labels:
    bot: conformitron
data:
  Namespace: newrelic
  prNumber: "282"
  commitHash: c64099ddb7edb475bf728239a08313ba5e37e1f7
  deployed: "1720558437"
  env: vsphere
