apiVersion: v1
kind: ConfigMap
metadata:
  name: newrelic-configmap
  namespace: newrelic
  labels:
    bot: conformitron
data:
  Namespace: newrelic
  prNumber: "212"
  commitHash: 6ee6c337fb1e8cb036584696d7018d833e871246
  deployed: "1707840163"
  env: cloud
