site_name: Amazon EKS Anywhere (EKS-A) Conformance and Validation Framework
repo_name: "aws-samples/eks-anywhere-addons"
repo_url: "https://github.com/aws-samples/eks-anywhere-addons"
docs_dir: "docs"
theme:
  name: material
  features:
    - tabs
nav:
  - Validated Partners: 
    - BareMetal: 'docs/Validated_Partners/baremetal_partners.md'
    - Nutanix: 'docs/Validated_Partners/nutanix_partners.md'
    - Rover: 'docs/Validated_Partners/rover_partners.md'
    - Snow: 'docs/Validated_Partners/snow_partners.md'
    - vSphere: 'docs/Validated_Partners/vsphere_partners.md'
markdown_extensions:
  - def_list
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
plugins:
  - search