site_name: Amazon EKS Anywhere (EKS-A) Conformance and Validation Framework
repo_name: "aws-samples/eks-anywhere-addons"
repo_url: "https://github.com/aws-samples/eks-anywhere-addons"
docs_dir: "docs"
theme:
  name: material
  features:
    - tabs
nav:
- Home:
  - Overview: index.md
extra_css:
- css/material.css
- css/mkdocstrings.css

markdown_extensions:
  - def_list
  - admonition
  - callouts
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: "¤"
plugins:
  - search