apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: botkube-general-secret
  namespace: botkube
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: eksa-configmap-store #The secret store name we have just created.
    kind: ClusterSecretStore
  target:
    name: botkube-general-secrets # Secret name in k8s
  data:
  - secretKey: snow-cluster-name # which key it's going to be stored
    remoteRef:
      key: /eksadeploymentModel/snow/cluster-name # Our secret-name goes here
  - secretKey: snow-slack-channel-name # which key it's going to be stored
    remoteRef:
      key: /eksadeploymentModel/snow/slack-channel-name # Our secret-name goes here