apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    aws.conformance.vendor: solo.io
    aws.conformance.vendor-solution: solo-istiod
    aws.conformance.vendor-solution-version: 1.18.3-eks-a