apiVersion: v1
kind: ConfigMap
metadata:
  name: komodor-configmap
  namespace: komodor
  labels:
    bot: conformitron
data:
  Namespace: komodor
  prNumber: "212"
  commitHash: c96ebaf8f8bbb188ed8217639eae25a341e1eabb
  deployed: "1707771255"
  env: common
