apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vsphere-snapshot-restored-claim
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 4Gi
  dataSource:
    name: vsphere-volume-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io