---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sysdig
  namespace: sysdig
spec:
  chart:
    spec:
      chart: sysdig-deploy
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: sysdig
        namespace: flux-system
      version: 1.5.46
  interval: 30s
  values:
    global:
      sysdig:
        region: us2   # us1 | us2 | us3 | us4 | eu1 | au1
      kspm:
        deploy: false # Disabled by default. Take care of the resources if you want to activate this option.
      clusterConfig:
        name: mycluster
    agent:
      tolerations: []
      # resourceProfile: custom
      # resources:
      #  requests:
      #    cpu:600m
      #    memory: 1G
      #  limits:
      #    cpu: 1500m
      #    memory: 1G
      sysdig:
        settings:
          collector_port: 6443
    nodeAnalyzer:
      nodeAnalyzer:
        benchmarkRunner:
          deploy: false
      secure:
        vulnerabilityManagement:
          newEngineOnly: true
  valuesFrom:
  - kind: Secret
    name: sysdig-access-key
    valuesKey: secret-sysdig-key
    targetPath: global.sysdig.accessKey
