apiVersion: v1
kind: ConfigMap
metadata:
  name: solo-istio-system-configmap
  namespace: solo-istio-system
  labels:
    bot: conformitron
data:
  Namespace: solo-istio-system
  prNumber: "32"
  commitHash: 4721eb46c10ed73754499e33f81fcd98a8ae8dc9
  deployed: "1714598609"
  env: common
