apiVersion: batch/v1
kind: Job
metadata:
  name: solo-istiod-healthtest
  namespace: istio-system  
spec:
  backoffLimit: 1
  template:
    spec:
      containers:
      - name: solo-istiod-healthtest
        image: curlimages/curl:latest
        command:
        - /bin/sh
        - -c
        - >-
            # Make a request to the Istiod service and store the HTTP status code
            HTTP_STATUS=$(curl -o /dev/null -s -w "%{http_code}\n" --location --insecure "https://istiod.istio-system.svc.cluster.local:15012")
            
            echo "Checking HTTP status code from Istiod service."
            
            # Check if the HTTP status code is 200 (OK)
            if [ "$HTTP_STATUS" -eq 200 ]; then
              echo "Received 200 OK from Istiod service. Successful."
              exit 0
            else
              echo "Istiod service check failed with status code: $HTTP_STATUS"
              exit 1
            fi        
      restartPolicy: Never
