apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openebs-claim
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-jiva-csi-default
  resources:
    requests:
      storage: 4Gi