---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: botkube
  namespace: botkube
spec:
  chart:
    spec:
      chart: botkube
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: botkube
        namespace: flux-system
      version: 0.12.4
  interval: 1m0s
  targetNamespace: botkube
  values: 
    communications:
      slack:
        enabled: true
  valuesFrom:
  - kind: ConfigMap
    name: botkube-configmap
    valuesKey: slack-channel-name
    targetPath: communication.slack.channel
  - kind: Secret
    name: botkube-secret
    valuesKey: botkube-token
    targetPath: communication.slack.token
  - kind: ConfigMap
    name: botkube-configmap
    valuesKey: cluster-name
    targetPath: config.settings.clustername

