---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: botkube
  namespace: botkube
spec:
  chart:
    spec:
      chart: botkube
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: botkube
        namespace: flux-system
      version: 0.13.0
  interval: 1m0s
  targetNamespace: botkube
  values: 
    communications:
      default-group:
        slack:
          enabled: true
    executors:
      kubectl-read-only:
        kubectl: enabled
    image:
      repository: botkube/botkube
      tag: v0.13.0
  valuesFrom:
  - kind: ConfigMap
    name: botkube-external-configmap
    valuesKey: slack-channel-name
    targetPath: communications.default-group.slack.channels.default.name
  - kind: Secret
    name: botkube-secret
    valuesKey: botkube-token
    targetPath: communications.default-group.slack.token
  - kind: ConfigMap
    name: botkube-external-configmap
    valuesKey: cluster-name
    targetPath: settings.clusterName

