apiVersion: v1
kind: ConfigMap
metadata:
  name: solo-istio-system-configmap
  namespace: solo-istio-system
  labels:
    bot: conformitron
data:
  Namespace: solo-istio-system
  prNumber: "261"
  commitHash: bed0ffba0015f90ea2fb6ffae61336f7f73126e4
  deployed: "1714660209"
  env: common
