apiVersion: v1
kind: ConfigMap
metadata:
  name: pass-fork-prod-configmap
  namespace: pass-fork-prod
  labels:
    bot: conformitron
data:
  Namespace: pass-fork-prod
  prNumber: "2"
  commitHash: 3a5ed0f7b85adf486c1c282725a2b37d867fbc3d
  deployed: "1703194367"
