apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: pass-fork-prod
  name: liveliness-check
  labels:
    app: liveliness-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: liveliness
  template:
    metadata:
      labels:
        app: liveliness
    spec:
      containers:
        - name: liveness
          image: registry.k8s.io/busybox
          args:
            - /bin/sh
            - -c
            - while true; do touch /tmp/healthy; sleep 600; done
          livenessProbe:
            exec:
              command:
                - cat
                - /tmp/healthy
            initialDelaySeconds: 5
            periodSeconds: 5
