apiVersion: v1
kind: ConfigMap
metadata:
  name: pulumi-configmap
  namespace: pulumi
  labels:
    bot: conformitron
data:
  Namespace: pulumi
  prNumber: "35"
  commitHash: 12f7d34d701c7f3ec9cda2e1d01f19a53a5ac407
  deployed: "1714605481"
  env: common
