apiVersion: v1
kind: ConfigMap
metadata:
  name: pat-ns-configmap
  namespace: pat-ns
  labels:
    bot: conformitron
data:
  Namespace: pat-ns
  prNumber: "3"
  commitHash: 78a22d0626daa77a7a98ef11b9b9a7de87911571
  deployed: "1705693728"
  env: common
