apiVersion: v1
kind: Namespace
metadata:
  name: kong
  labels:
    aws.conformance.vendor: kong
    aws.conformance.vendor-solution: kong-enterprise
    aws.conformance.vendor-solution-version: 2.27.0