apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tetrate-istiod-job-role
  namespace: tetrate-istio
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec", "services"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["networking.istio.io"]
    resources: ["gateways", "virtualservices", "destinationrules", "serviceentries", "envoyfilters"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tetrate-istiod-job-rolebinding
  namespace: tetrate-istio
subjects:
  - kind: ServiceAccount
    name: default
    namespace: tetrate-istio
roleRef:
  kind: Role
  name: tetrate-istiod-job-role
  apiGroup: rbac.authorization.k8s.io
