apiVersion: v1
kind: ConfigMap
metadata:
  name: vmware-system-csi-configmap
  namespace: vmware-system-csi
  labels:
    bot: conformitron
data:
  Namespace: vmware-system-csi
  prNumber: "299"
  commitHash: eb7ee15fc839d39741bf24b7a84831be349423a2
  deployed: "1728935567"
  env: vsphere
