apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: eksa-secret-store
spec:
  provider:
    aws:  # set secretStore provider to AWS.
      service: SecretsManager # Configure service to be secrets manager
      region: us-west-2  # Region where the secret is.
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-secret # References the secret we created
            namespace: default
            key: access-key
          secretAccessKeySecretRef:
            name: aws-secret
            namespace: default
            key: secret