apiVersion: v1
kind: ConfigMap
metadata:
  name: lacework-observation-configmap
  namespace: lacework
  labels:
    bot: conformitron
data:
  Namespace: lacework
  lastApprovedPrNumber: "103"
  lastPrCommitHash: 6a240de0bf1877ffe4d3bdd80cb878c1666dd644
  lastPointOfContact: "jefferyfry"
  approved: "1716226456"
  env: common
  testJobName: lacework-agent-testjob
