apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: vmware-csi
  namespace: flux-system
spec:
  path: "./eks-anywhere-vsphere/Addons/Core/storage-driver/vmware-csi"
  sourceRef:
    kind: GitRepository
    name: addons
    namespace: flux-system
  interval: 5m0s
  prune: true
---