---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vmware-csi-namespace-kustomization
  namespace: flux-system
  labels:
    app: vmware-csi-driver
spec:
  interval: 1m0s
  path: ./eks-anywhere-vsphere/Addons/Core/storage-driver/vmware-csi
  prune: true
  sourceRef:
    kind: GitRepository
    name: addons
