apiVersion: v1
kind: ConfigMap
metadata:
  name: newrelic-configmap
  namespace: newrelic
  labels:
    bot: conformitron
data:
  Namespace: newrelic
  prNumber: "33"
  commitHash: e1a1ad031a6d122bb290c518fa40ce61f8428602
  deployed: "1714604677"
  env: baremetal
