apiVersion: v1
kind: ConfigMap
metadata:
  name: newrelic-configmap
  namespace: newrelic
  labels:
    bot: conformitron
data:
  Namespace: newrelic
  prNumber: "293"
  commitHash: 601e52a986369a07ea336f0c2b97ec14cf193d90
  deployed: "1727908003"
  env: baremetal
