apiVersion: v1
kind: ConfigMap
metadata:
  name: newrelic-configmap
  namespace: newrelic
  labels:
    bot: conformitron
data:
  Namespace: newrelic
  prNumber: "274"
  commitHash: 27fac3f06098a70ae0371a923c284285b9a66ca7
  deployed: "1716293029"
  env: baremetal
