apiVersion: v1
kind: ConfigMap
metadata:
  name: newrelic-configmap
  namespace: newrelic
  labels:
    bot: conformitron
data:
  Namespace: newrelic
  prNumber: "276"
  commitHash: 662f578a7b8f284d2602e51cd2c3a6b1df5c742f
  deployed: "1717003338"
  env: baremetal
