apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openebs-snapshot-restored-claim
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-jiva-csi-default
  resources:
    requests:
      storage: 4Gi
  dataSource:
    name: openebs-volume-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io