apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vsphere-claim
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 4Gi