apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: aws-ebs-csi-driver
  namespace: flux-system
resources:
  - helm-repo.yaml
  - helm-release.yaml
  - snapshotclass.yaml
  - storage-class.yaml