apiVersion: v1
kind: ConfigMap
metadata:
  name: cross-fork-prod-configmap
  namespace: cross-fork-prod
  labels:
    bot: conformitron
data:
  Namespace: cross-fork-prod
  prNumber: "1"
  commitHash: 706d791a080d6060c59aacf323ed99527dedf5ac
  deployed: 1703193748
