apiVersion: v1
kind: ConfigMap
metadata:
  name: pass-fork-prod-configmap
  namespace: pass-fork-prod
  labels:
    bot: conformitron
data:
  Namespace: pass-fork-prod
  prNumber: "2"
  commitHash: aeb3413fb887f44ab723911f65cc8af7d4ffb3b0
  deployed: 1703194005
