apiVersion: v1
kind: ConfigMap
metadata:
  name: cross-fork-prod-configmap
  namespace: cross-fork-prod
  labels:
    bot: conformitron
data:
  Namespace: cross-fork-prod
  prNumber: "1"
  commitHash: 93320d544cf8f9693ea56356d4200373efbed3cc
  deployed: "1704862252"
  env: common
