apiVersion: v1
kind: ConfigMap
metadata:
  name: cross-fork-configmap
  namespace: cross-fork-prod
  labels:
    bot: conformitron
data:
  Namespace: cross-fork-prod
  prNumber: "1"
  commitHash: 41cede5e707da5854c7ca05e589b031e88d68bbd
  deployed: "2023-12-18T22:40:00.494301"
