apiVersion: v1
kind: ConfigMap
metadata:
  name: aqua-configmap
  namespace: aqua
  labels:
    bot: conformitron
data:
  Namespace: aqua
  prNumber: "216"
  commitHash: c639ab69d55f43c8a03b2a1dd2e478b6a5738a42
  deployed: "1709646499"
  env: common
