apiVersion: v1
kind: ConfigMap
metadata:
  name: aqua-configmap
  namespace: aqua
  labels:
    bot: conformitron
data:
  Namespace: aqua
  prNumber: "216"
  commitHash: c438f8ea564d5dfcd0de7992a5e59b482321b3b3
  deployed: "1710235854"
  env: common
