apiVersion: v1
kind: ConfigMap
metadata:
  name: aqua-configmap
  namespace: aqua
  labels:
    bot: conformitron
data:
  Namespace: aqua
  prNumber: "216"
  commitHash: 787398bff8675add2f5117d8ba2fe9620afd72af
  deployed: "1710162879"
  env: common
