apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: test-app
  namespace: flux-system
spec:
  path: "./eks-anywhere-baremetal/Testers/Core/storage-tester/test-app"
  sourceRef:
    kind: GitRepository
    name: addons
    namespace: flux-system
  interval: 5m0s
  prune: true
---