apiVersion: v1
kind: ConfigMap
metadata:
  name: tetrate-istio-system-configmap
  namespace: tetrate-istio-system
  labels:
    bot: conformitron
data:
  Namespace: tetrate-istio-system
  prNumber: "245"
  commitHash: 9ccaafa3ed45b7139b12f1c208c222ab919752c8
  deployed: "1713360406"
  env: common
