apiVersion: v1
kind: ConfigMap
metadata:
  name: tetrate-istio-system-configmap
  namespace: tetrate-istio-system
  labels:
    bot: conformitron
data:
  Namespace: tetrate-istio-system
  prNumber: "245"
  commitHash: aef1e4b3cc5878318b6904f43fff10de372a6812
  deployed: "1713248858"
  env: common
