apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    aws.conformance.vendor: tetrate.io
    aws.conformance.vendor-solution: tetrate-istio-distribution
    aws.conformance.vendor-solution-version: 1.18.1
