apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tetrate-istiod
  namespace: tetrate-istio
spec:
  chart:
    spec:
      chart: istiod
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: tetrate-istio-charts
        namespace: flux-system
      version: 1.18.1
  interval: 1m0s
