apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: snapshot-crds
  namespace: flux-system
spec:
  path: "./eks-anywhere-baremetal/Addons/Core/storage-driver/snapshot-crds"
  sourceRef:
    kind: GitRepository
    name: addons
    namespace: flux-system
  interval: 5m0s
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: snapshot-controller
  namespace: flux-system
spec:
  dependsOn:
    - name: snapshot-crds
  path: "./eks-anywhere-baremetal/Addons/Core/storage-driver/snapshot-controller"
  sourceRef:
    kind: GitRepository
    name: addons
    namespace: flux-system
  interval: 5m0s
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: csi-snapshotter
  namespace: flux-system
spec:
  dependsOn:
    - name: snapshot-controller
  path: "./eks-anywhere-baremetal/Addons/Core/storage-driver/csi-snapshotter"
  sourceRef:
    kind: GitRepository
    name: addons
    namespace: flux-system
  interval: 5m0s
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: openebs
  namespace: flux-system
spec:
  dependsOn:
    - name: csi-snapshotter
  path: "./eks-anywhere-baremetal/Addons/Core/storage-driver/openebs"
  sourceRef:
    kind: GitRepository
    name: addons
    namespace: flux-system
  interval: 5m0s
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: classes
  namespace: flux-system
spec:
  dependsOn:
    - name: local-ebs
  path: "./eks-anywhere-baremetal/Addons/Core/storage-driver/classes"
  sourceRef:
    kind: GitRepository
    name: addons
    namespace: flux-system
  interval: 5m0s
  prune: true
---