apiVersion: v1
kind: ConfigMap
metadata:
  name: newrelic-configmap
  namespace: newrelic
  labels:
    bot: conformitron
data:
  Namespace: newrelic
  prNumber: "213"
  commitHash: 739f1d9859c0b3bcff90b33232921a6117e37ce6
  deployed: "1707825807"
  env: snow
