apiVersion: v1
kind: ConfigMap
metadata:
  name: newrelic-configmap
  namespace: newrelic
  labels:
    bot: conformitron
data:
  Namespace: newrelic
  prNumber: "295"
  commitHash: 66f60230b782af7b5b4a9a4a4daa86187ff49008
  deployed: "1728389015"
  env: snow
