apiVersion: v1
kind: ConfigMap
metadata:
  name: newrelic-configmap
  namespace: newrelic
  labels:
    bot: conformitron
data:
  Namespace: newrelic
  prNumber: "185"
  commitHash: 94f3db511e3fa7dca0b892a36f9376cbe352765a
