apiVersion: v1
kind: ConfigMap
metadata:
  name: newrelic-configmap
  namespace: newrelic
  labels:
    bot: conformitron
data:
  Namespace: newrelic
  prNumber: "207"
  commitHash: 7a49b23700ced8e7ff716fc4b449aa5b493842c7
  deployed: "1707319795"
  env: snow
