apiVersion: v1
kind: ConfigMap
metadata:
  name: newrelic-configmap
  namespace: newrelic
  labels:
    bot: conformitron
data:
  Namespace: newrelic
  prNumber: "271"
  commitHash: 65e011c8786cb550aee724cd6065f94db8c6d019
  deployed: "1715813128"
  env: snow
