apiVersion: v1
kind: ConfigMap
metadata:
  name: newrelic-configmap
  namespace: newrelic
  labels:
    bot: conformitron
data:
  Namespace: newrelic
  prNumber: "285"
  commitHash: 9e4ceccb42b2ad2ddd195313e36633c8ac32903c
  deployed: "1721736209"
  env: snow
