apiVersion: v1
kind: ConfigMap
metadata:
  name: newrelic-configmap
  namespace: newrelic
  labels:
    bot: conformitron
data:
  Namespace: newrelic
  prNumber: "34"
  commitHash: d61e87720d747c71182184fdc1b529fe1f262241
  deployed: "1714604927"
  env: snow
