apiVersion: v1
kind: ConfigMap
metadata:
  name: newrelic-configmap
  namespace: newrelic
  labels:
    bot: conformitron
data:
  Namespace: newrelic
  prNumber: "223"
  commitHash: 7f4f2021ebc4c195a0ae65213145404d23c98869
  deployed: "1709035408"
  env: snow
