apiVersion: batch/v1
kind: Job
metadata:
  name: newrelic-testjob
  namespace: newrelic
spec:
  backoffLimit: 1
  template:
    spec:
      serviceAccount: newrelic-testjob-service-account
      initContainers:
        - name: kubectl
          image: bitnami/kubectl
          command: ['sh', '-c', "kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=nri-metadata-injection -n newrelic"]
      containers:
      - name: test-container
        image: busybox
        command: [ "sh", "-c"]
        args:
        - >-
          if [[ -z "${NEW_RELIC_METADATA_KUBERNETES_NODE_NAME}" ]]; then
            echo "FAILURE"
            exit 1
          else
            echo "SUCCESS"
          fi
      restartPolicy: Never