---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: newrelic-testjob-service-account
  namespace: newrelic
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: newrelic-testjob-clusterrole
  namespace: newrelic
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: newrelic-testjob-clusterrole-binding
  namespace: newrelic
subjects:
- kind: ServiceAccount
  name: newrelic-testjob-service-account
  namespace: newrelic
roleRef:
  kind: ClusterRole
  name: newrelic-testjob-clusterrole
  apiGroup: rbac.authorization.k8s.io
