version: 0.2
env:
  variables:
    CONTEXT_LOCATION:
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - n 18.12.1
      - |
        if [ ! -z "${COMMIT_ID}" ]; then 
          git fetch origin pull/${PR_NUMBER}/head:pr
          git checkout developer
          # git merge needs user details, but we don't push anything, so the contents are unimportant
          git -c "user.name=CI Bot" -c "user.email=dev@null" merge --no-edit ${COMMIT_ID}
        fi
  pre_build:
    commands:
      - echo 'pre build'
  build:
    commands:
      - echo 'deploy'
    finally:
      - echo 'destroy'