name: Run CI for ISV Addons

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.12.1]
    steps:
    - name: Checkout and Merge to Developer branch
      run: |
        PR_NUMBER=$(echo "$GITHUB_REF" | awk -F / '{print $3}')
        COMMIT_ID=$(echo $GITHUB_SHA | cut -c1-7)
        echo "Commit ID = " ${COMMIT_ID}
        echo "PR = " ${PR_NUMBER}
        if [ ! -z "${COMMIT_ID}" ]; then 
          git fetch origin pull/${PR_NUMBER}/head:pr
          git checkout developer
          # git merge needs user details, but we don't push anything, so the contents are unimportant
          git -c "user.name=CI Bot" -c "user.email=dev@null" merge --no-edit ${COMMIT_ID}
        fi