name: PRs to Main
on: 
  pull_request:
    branches: [main]
    types: [closed]
jobs:
  merge-master-back-to-dev:
    if: github.event.pull_request.merged == true
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set Git config
      run: |
          git config --local user.email "dev@null"
          git config --local user.name "CI Bot"
    - name: Merge main back to dev
      run: |
          git fetch --unshallow
          git checkout dev
          git pull
          git merge --no-ff main -m "Auto-merge main back to dev"
          git push
