name: Run CI for ISV Addons

on:
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Find Namespace YAML
      id: find-namespace-yaml
      run: |
        files=$(curl -s "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files" | jq -r '.[].filename')
        namespace_file=$(echo "$files" | grep "namespace.yaml")
        if [ -n "$namespace_file" ]; then
          namespace_name=$(grep -E '^\s*metadata:\s*$|^\s*name:\s*' "$namespace_file" | awk -F':' '{gsub(/ /, "", $2); print $2}')
          echo "$namespace_name" > namespace.tmp
          cat namespace.tmp
        fi
          
    - name: Generate the config map file content and create ConfigMap File
      run: |
          namespace_name=$(cat namespace.tmp)
          namespace=$(echo $namespace_name | xargs echo -n)
          echo $namespace
          config_map_file="config-map-$namespace-${{ github.event.pull_request.number }}.yml"
          echo $config_map_file
          echo "apiVersion: v1" >> $config_map_file
          echo "kind: ConfigMap" >> $config_map_file
          echo "metadata:" >> $config_map_file
          echo "  name: $namespace-configmap" >> $config_map_file
          echo "data:" >> $config_map_file
          echo "  Namespace: ${namespace}" >> $config_map_file
          echo "  prNumber: ${{ github.event.pull_request.number }}" >> $config_map_file          
          cat $config_map_file

    - name: Set Git config
      run: |
          git config --local user.email "dev@null"
          git config --local user.name "CI Bot"

    - name: Add File and Merge to Developer branch
      run: |
        commitId=$(echo $GITHUB_SHA | cut -c1-7)
        echo "Commit ID = " ${commitId}
        if [ ! -z "${commitId}" ]; then 
          git fetch --all
          git checkout dev
          git pull origin pull/${{ github.event.pull_request.number }}/head:dev
          git add $config_map_file
          git commit -m "Add config map for namespace $namespace and PR number ${{ github.event.pull_request.number }}"
          git push origin dev
        fi