---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kyverno
spec:
  chart:
    spec:
      chart: kyverno
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: nirmata
        namespace: flux-system
      version: "1.6.8"
  interval: 2m0s
  releaseName: kyverno
  targetNamespace: kyverno
  valuesFrom:
  - kind: Secret
    name: nirmata-secret
    valuesKey: nirmata-license-key
    targetPath: licenseManager.licenseKey
