---
apiVersion: v1
kind: Namespace
metadata:
  name: kyverno
  labels:
      aws.conformance.vendor: nirmata
      aws.conformance.vendor-solution: enterprise-kyverno
      aws.conformance.vendor-solution-version: "1.6.10"
