apiVersion: batch/v1
kind: Job
metadata:
  name: lacework-agent-testjob
  namespace: lacework
spec:
  backoffLimit: 1
  template:
    spec:
      containers:
        - name: job
          image: 'alpine/k8s:1.26.2'
          imagePullPolicy: Always
          command:
            - /bin/bash
          args:
            - '-c'
            - >-
              kubectl wait pods -n lacework -l name=lacework-agent --for condition=Ready --timeout=90s
      restartPolicy: Never